# Generated by Django 4.1.7 on 2023-03-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0003_alter_quote_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='tags',
        ),
    ]
