# Generated by Django 4.1.7 on 2023-03-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0004_remove_quote_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='tags',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
