# Generated by Django 4.1.7 on 2023-03-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0011_tag_remove_quote_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='tittle',
        ),
        migrations.AddField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='quotes', to='quoteapp.tag'),
        ),
    ]
