# Generated by Django 4.1.7 on 2023-03-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0012_rename_tag_tag_tittle_quote_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(related_name='quotes', to='quoteapp.tag'),
        ),
    ]
