# Generated by Django 4.1.7 on 2023-03-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0016_alter_author_born_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tittle',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
